import '../models/innovator.dart';
import '../models/quiz_question.dart';

const innovators = <Innovator>[
  Innovator(
    id: 'marie-curie',
    name: 'Marie Curie',
    country: 'Poland / France',
    region: 'Europe',
    field: 'Physics & Chemistry',
    birthYear: 1867,
    deathYear: 1934,
    summary: 'Pioneer of research into radioactivity and two-time Nobel laureate.',
    biography: 'Marie Curie was a physicist and chemist whose work transformed the study of radioactivity. She and Pierre Curie investigated radioactive materials and helped establish new scientific methods and concepts.',
    achievements: ['Research on radioactivity', 'Discovery of polonium and radium', 'Nobel Prize in Physics', 'Nobel Prize in Chemistry'],
    tags: ['science', 'women', 'medicine'],
  ),
  Innovator(
    id: 'nikola-tesla',
    name: 'Nikola Tesla',
    country: 'Serbia / United States',
    region: 'Europe',
    field: 'Electrical Engineering',
    birthYear: 1856,
    deathYear: 1943,
    summary: 'Inventor and electrical engineer whose work advanced alternating-current systems.',
    biography: 'Nikola Tesla contributed to the development of alternating-current electrical systems, motors, transformers and radio-related technology.',
    achievements: ['AC induction motor', 'Polyphase AC systems', 'Electrical engineering patents', 'Wireless technology experiments'],
    tags: ['technology', 'engineering'],
  ),
  Innovator(
    id: 'ada-lovelace',
    name: 'Ada Lovelace',
    country: 'United Kingdom',
    region: 'Europe',
    field: 'Computing',
    birthYear: 1815,
    deathYear: 1852,
    summary: 'Mathematician whose notes on the Analytical Engine anticipated computer programming.',
    biography: 'Ada Lovelace worked with Charles Babbage on the Analytical Engine. Her published notes included an algorithm often described as an early example of computer programming.',
    achievements: ['Analytical Engine notes', 'Early algorithmic computing concepts'],
    tags: ['technology', 'women', 'mathematics'],
  ),
  Innovator(
    id: 'philip-emeagwali',
    name: 'Philip Emeagwali',
    country: 'Nigeria',
    region: 'Africa',
    field: 'Computing',
    birthYear: 1954,
    deathYear: null,
    summary: 'Nigerian-born computer scientist and engineer associated with high-performance computing.',
    biography: 'Philip Emeagwali is a Nigerian-born computer scientist and engineer known for work involving massively parallel computing. His career is frequently discussed in histories of African contributions to computing.',
    achievements: ['Parallel computing research', 'High-performance computing advocacy', 'Science and technology education'],
    tags: ['africa', 'nigeria', 'technology', 'computing'],
  ),
  Innovator(
    id: 'francisca-okeke',
    name: 'Francisca Nneka Okeke',
    country: 'Nigeria',
    region: 'Africa',
    field: 'Physics',
    birthYear: 1956,
    deathYear: null,
    summary: 'Nigerian physicist known for research and leadership in space and atmospheric science.',
    biography: 'Francisca Nneka Okeke is a Nigerian physicist whose research includes ionospheric and atmospheric phenomena. She has also contributed to science education and academic leadership.',
    achievements: ['Ionospheric research', 'Space science research', 'Science education and leadership'],
    tags: ['africa', 'nigeria', 'science', 'women', 'space'],
  ),
  Innovator(
    id: 'garrett-morgan',
    name: 'Garrett Morgan',
    country: 'United States',
    region: 'Americas',
    field: 'Invention',
    birthYear: 1877,
    deathYear: 1963,
    summary: 'African-American inventor known for safety equipment and traffic-control technology.',
    biography: 'Garrett Morgan developed inventions including a safety hood and an early traffic signal. He also operated a successful business and promoted civic causes.',
    achievements: ['Safety hood', 'Traffic signal', 'Business entrepreneurship'],
    tags: ['technology', 'engineering', 'african-diaspora'],
  ),
  Innovator(
    id: 'katherine-johnson',
    name: 'Katherine Johnson',
    country: 'United States',
    region: 'Americas',
    field: 'Mathematics & Space',
    birthYear: 1918,
    deathYear: 2020,
    summary: 'Mathematician whose calculations supported major U.S. human spaceflight missions.',
    biography: 'Katherine Johnson worked as a mathematician at NASA and its predecessor organizations. Her trajectory calculations supported early crewed space missions.',
    achievements: ['Spaceflight trajectory calculations', 'Mercury program work', 'Apollo mission calculations'],
    tags: ['space', 'women', 'mathematics', 'african-diaspora'],
  ),
  Innovator(
    id: 'tim-berners-lee',
    name: 'Tim Berners-Lee',
    country: 'United Kingdom',
    region: 'Europe',
    field: 'Computing',
    birthYear: 1955,
    deathYear: null,
    summary: 'Computer scientist who invented the World Wide Web.',
    biography: 'Tim Berners-Lee created the foundational technologies of the World Wide Web, including HTML, HTTP and URLs, while working at CERN.',
    achievements: ['World Wide Web', 'HTML', 'HTTP', 'URL system'],
    tags: ['technology', 'computing'],
  ),
];

const quizQuestions = <QuizQuestion>[
  QuizQuestion(
    question: 'Who is associated with the invention of the World Wide Web?',
    options: ['Tim Berners-Lee', 'Isaac Newton', 'Louis Pasteur', 'James Watt'],
    correctIndex: 0,
    explanation: 'Tim Berners-Lee created the foundational technologies of the World Wide Web at CERN.',
  ),
  QuizQuestion(
    question: 'Which Nigerian physicist is associated with ionospheric research?',
    options: ['Francisca Nneka Okeke', 'Ada Lovelace', 'Marie Curie', 'Katherine Johnson'],
    correctIndex: 0,
    explanation: 'Francisca Nneka Okeke is a Nigerian physicist known for ionospheric and atmospheric research.',
  ),
  QuizQuestion(
    question: 'Marie Curie worked primarily in which scientific areas?',
    options: ['Physics and Chemistry', 'Botany and Zoology', 'Geology and Astronomy', 'Economics and Law'],
    correctIndex: 0,
    explanation: 'Her major scientific work was in physics and chemistry, especially radioactivity.',
  ),
];
